### ISSUE TITLE
can't modify frozen String (FrozenError)

### ISSUE THREAD

**Issue by rahularoradfs** [yohasebe/wp2txt#12]
Hi @yohasebe,

I am able to successfully convert the latest enwiki Wikipedia dump using `wp2txt`:
```zsh
wp2txt --no-convert -i ./enwiki-20220801-pages-articles.xml.bz2 -o ./xml
```

However, when I try to extract text, category, or summary, I get a strange `FrozenError` that I'm not sure how to handle. Any suggestions for how to resolve this?
```zsh
sudo wp2txt -i ./xml -o ./text

Converting
Number of files being processed: 8871
Number of CPU cores being used:  8
/Library/Ruby/Gems/2.6.0/gems/wp2txt-1.1.1/bin/wp2txt:184:in `block (2 levels) in run': can't modify frozen String (FrozenError)
	from /Library/Ruby/Gems/2.6.0/gems/wp2txt-1.1.1/lib/wp2txt.rb:289:in `block in extract_text'
	from /Library/Ruby/Gems/2.6.0/gems/wp2txt-1.1.1/lib/wp2txt.rb:269:in `each'
	from /Library/Ruby/Gems/2.6.0/gems/wp2txt-1.1.1/lib/wp2txt.rb:269:in `extract_text'
	from /Library/Ruby/Gems/2.6.0/gems/wp2txt-1.1.1/bin/wp2txt:104:in `block in run'
	from /Library/Ruby/Gems/2.6.0/gems/parallel-1.22.1/lib/parallel.rb:587:in `call_with_index'
	from /Library/Ruby/Gems/2.6.0/gems/parallel-1.22.1/lib/parallel.rb:557:in `process_incoming_jobs'
	from /Library/Ruby/Gems/2.6.0/gems/parallel-1.22.1/lib/parallel.rb:537:in `block in worker'
	from /Library/Ruby/Gems/2.6.0/gems/parallel-1.22.1/lib/parallel.rb:528:in `fork'
	from /Library/Ruby/Gems/2.6.0/gems/parallel-1.22.1/lib/parallel.rb:528:in `worker'
	from /Library/Ruby/Gems/2.6.0/gems/parallel-1.22.1/lib/parallel.rb:519:in `block in create_workers'
	from /Library/Ruby/Gems/2.6.0/gems/parallel-1.22.1/lib/parallel.rb:518:in `each'
	from /Library/Ruby/Gems/2.6.0/gems/parallel-1.22.1/lib/parallel.rb:518:in `each_with_index'
	from /Library/Ruby/Gems/2.6.0/gems/parallel-1.22.1/lib/parallel.rb:518:in `create_workers'
	from /Library/Ruby/Gems/2.6.0/gems/parallel-1.22.1/lib/parallel.rb:457:in `work_in_processes'
	from /Library/Ruby/Gems/2.6.0/gems/parallel-1.22.1/lib/parallel.rb:294:in `map'
	from /Library/Ruby/Gems/2.6.0/gems/wp2txt-1.1.1/bin/wp2txt:102:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/wp2txt-1.1.1/bin/wp2txt:192:in `<top (required)>'
	from /usr/local/bin/wp2txt:23:in `load'
	from /usr/local/bin/wp2txt:23:in `<main>'
```

For context, I'm on a M1 MacBook Pro.

Thanks for your work creating this package!

**Comment by rahularoradfs** [comment]
Fixing my Ruby installation following the instructions [here](https://stackoverflow.com/questions/51126403/you-dont-have-write-permissions-for-the-library-ruby-gems-2-3-0-directory-ma) fixed the issue. In addition to this, I had to uninstall `wp2txt` from my system `gem` so `wp2txt` would run the `chruby gem` `wp2txt` instance.
