### ISSUE TITLE
-x option leads to error

### ISSUE THREAD

**Issue by Erstyx** [yohasebe/wp2txt#14]
On Windows, running a command like wp2txt -i ./wiki-20220820-pages-articles.xml -o . --no-category -x leads to the following error:

```
E:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/wp2txt-1.1.1/lib/wp2txt.rb:300:in 'delete': Permission denied @ apply2files - ./xhwiki-20220820-pages-articles-1.xml (Errno::EACCES)
         from E:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/wp2txt-1.1.1/lib/wp2txt.rb:300:in 'extract_text'
         from E:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/wp2txt-1.1.1/bin/wp2txt:104:in 'block in run'
         from E:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/wp2txt-1.1.1/bin/wp2txt:102:in 'each'
         from E:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/wp2txt-1.1.1/bin/wp2txt:102:in 'run'
         from E:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/wp2txt-1.1.1/bin/wp2txt:192:in '<top (required)>'
         from E:/Ruby32-x64/bin/wp2txt:32:in 'load'
         from E:/Ruby32-x64/bin/wp2txt:32:in '<main>'
```

**Comment by yohasebe** [comment]
Thank you again for your report. This issue has been addressed in the latest version (1.1.2).
